source 'https://rubygems.org'

gem 'rugged', '~> 0.27.0'
gem 'github-linguist', '~> 5.3.3', require: 'linguist'
gem 'gitlab-markup', '~> 1.6.2'
gem 'gitaly-proto', '~> 0.99.0', require: 'gitaly'
gem 'activesupport', '~> 4.2.10'
gem 'rdoc', '~> 4.2.2'
gem 'gitlab-gollum-lib', '~> 4.2', require: false
gem 'gitlab-gollum-rugged_adapter', '~> 0.4.4', require: false
gem 'grpc', '~> 1.11.0'
gem 'sentry-raven', '~> 2.7.2', require: false

# random gem versions to match gitlab-ce
gem 'faraday', '~> 0.12.2'
gem 'json', '~> 1.8.6'
gem 'jwt', '~> 1.5.6'
gem 'rubocop', '~> 0.52.1'
gem 'rubocop-rspec', '~> 1.22.1'
gem 'rainbow', '~> 2.2.2'
gem 'minitest', '~> 5.7.0'

# Detects the open source license the repository includes
# This version needs to be in sync with GitLab CE/EE
gem 'licensee', '~> 8.9.0'

# Locked until https://github.com/google/protobuf/issues/4210 is closed
gem 'google-protobuf', '= 3.5.1'

group :development, :test do
  gem 'gitlab-styles', '~> 2.3.2', require: false
  gem 'rspec', require: false
end
