#!/bin/sh

set -ex

ref_snapshot=$(mktemp -t gitaly-create-bundle.XXXXXX)
echo '# gitaly bundle v1'
git for-each-ref --format='%(objectname) %(refname)' | tee "${ref_snapshot}"
echo
(
  awk '{print $1}' "${ref_snapshot}"
  rm "${ref_snapshot}"
  awk '/^$/ { exit } /^[^#]/ { print "^" $1 }'
) | git pack-objects --thin --stdout --non-empty --delta-base-offset
