#!/bin/sh

set -ex

ref_snapshot=$(mktemp -t gitaly-bundle-create.XXXXXX)

# Header
echo '# gitaly bundle v1'

# Ref dump
git for-each-ref --format='%(objectname) %(refname)' | tee "${ref_snapshot}"
echo

(
  # Tell pack-objects the objects we want to include
  awk '{print $1}' "${ref_snapshot}"
  rm "${ref_snapshot}"

  # The previous snapshot should be on stdin. Use it to tell pack-objects
  # which objects we already have. The previous snapshot may be empty
  # (/dev/null). This awk command will only consume the ref dump part of
  # stdin; pack data is not read.
  awk '/^$/ { exit } /^[^#]/ { print $1 }' |\
    git cat-file --batch-check='%(objectname)' |\
    awk '!/ missing$/ { print "^" $1 }'
) | git pack-objects --thin --stdout --non-empty --delta-base-offset
