#!/usr/bin/env ruby

# Tests inputs to pre-receive

abort("FAIL") if $stdin.read.empty?
abort("FAIL") if %w[GL_ID GL_REPOSITORY GL_PROTOCOL GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES].any? { |k| ENV[k].empty? }

puts "OK"

