// Code generated by protoc-gen-go. DO NOT EDIT.
// source: linter/testdata/invalid.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/gitlab-org/gitaly/internal/praefect/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InvalidRequest did not set the operation type to a valid option
type InvalidRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidRequest) Reset()         { *m = InvalidRequest{} }
func (m *InvalidRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidRequest) ProtoMessage()    {}
func (*InvalidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd62f399b3bf72d3, []int{0}
}

func (m *InvalidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidRequest.Unmarshal(m, b)
}
func (m *InvalidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidRequest.Marshal(b, m, deterministic)
}
func (m *InvalidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidRequest.Merge(m, src)
}
func (m *InvalidRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidRequest.Size(m)
}
func (m *InvalidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InvalidRequest)(nil), "test.InvalidRequest")
}

func init() { proto.RegisterFile("linter/testdata/invalid.proto", fileDescriptor_bd62f399b3bf72d3) }

var fileDescriptor_bd62f399b3bf72d3 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0xc9, 0xcc, 0x2b,
	0x49, 0x2d, 0xd2, 0x2f, 0x49, 0x2d, 0x2e, 0x49, 0x49, 0x2c, 0x49, 0xd4, 0xcf, 0xcc, 0x2b, 0x4b,
	0xcc, 0xc9, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x4b, 0xf1, 0xe4,
	0x17, 0x94, 0x54, 0x16, 0xa4, 0x42, 0xc4, 0x94, 0x24, 0xb8, 0xf8, 0x3c, 0x21, 0x8a, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xac, 0xd8, 0x3e, 0x4d, 0xd7, 0x60, 0xe2, 0x60, 0x48, 0x62, 0x03,
	0x2b, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xec, 0x76, 0x32, 0x05, 0x55, 0x00, 0x00, 0x00,
}
