# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ha-cleanup.proto

require 'google/protobuf'

require 'shared_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gitaly.CleanupOrphanedReposRequest" do
    repeated :valid_repositories, :message, 1, "gitaly.Repository"
  end
  add_message "gitaly.CleanupOrphanedReposResponse" do
  end
end

module Gitaly
  CleanupOrphanedReposRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CleanupOrphanedReposRequest").msgclass
  CleanupOrphanedReposResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CleanupOrphanedReposResponse").msgclass
end
