# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: health.proto for package 'gitaly'

require 'grpc'
require 'health_pb'

module Gitaly
  module Health
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.Health'

      rpc :Check, HealthCheckRequest, HealthCheckResponse
      rpc :Watch, HealthCheckRequest, stream(HealthCheckResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
